"""PyTorch-style nn.modules namespace."""

from activations.activations import ELU, GELU, LeakyReLU, Mish, PReLU, ReLU, SiLU, Sigmoid, Softmax, SwiGLU, Tanh
from attention.attention import (
    FlashMultiHeadAttention,
    FlashMultiHeadAttentionV2,
    FlashMultiHeadAttentionV3,
    GroupedQueryAttention,
    LinearMultiHeadAttention,
    MultiHeadAttention,
    MultiLatentAttention,
    MultiQueryAttention,
    PagedMultiHeadAttention,
    SparseMultiHeadAttention,
    flash_attention,
    flash_attention_v2,
    flash_attention_v3,
    linear_attention,
    paged_attention,
    scaled_dot_product_attention,
    sparse_attention,
)
from convolution.convolutions import AvgPool2d, BatchNorm2d, Conv2d, MaxPool2d
from embeddings.embeddings import (
    Embedding,
    EmbeddingLayer,
    PositionalEncoding,
    create_sinusoidal_embeddings,
)
from layers.layers import Dropout, Layer, Linear, Sequential
from losses.losses import BinaryCrossEntropyLoss, CrossEntropyLoss, MSELoss
from transformers.transformers import GPT, LayerNorm, MLP, TransformerBlock, create_causal_mask

from . import (
    activation,
    attention,
    container,
    conv,
    linear,
    loss,
    normalization,
    pooling,
    sparse,
    transformer,
)

Module = Layer

__all__ = [
    "activation",
    "attention",
    "AvgPool2d",
    "BatchNorm2d",
    "BinaryCrossEntropyLoss",
    "container",
    "Conv2d",
    "CrossEntropyLoss",
    "Dropout",
    "Embedding",
    "EmbeddingLayer",
    "ELU",
    "GELU",
    "GPT",
    "Layer",
    "LayerNorm",
    "LeakyReLU",
    "Linear",
    "linear",
    "loss",
    "MaxPool2d",
    "Mish",
    "MLP",
    "Module",
    "MSELoss",
    "MultiHeadAttention",
    "FlashMultiHeadAttention",
    "FlashMultiHeadAttentionV2",
    "FlashMultiHeadAttentionV3",
    "GroupedQueryAttention",
    "MultiQueryAttention",
    "MultiLatentAttention",
    "SparseMultiHeadAttention",
    "LinearMultiHeadAttention",
    "PagedMultiHeadAttention",
    "normalization",
    "PReLU",
    "PositionalEncoding",
    "pooling",
    "ReLU",
    "SiLU",
    "flash_attention",
    "flash_attention_v2",
    "flash_attention_v3",
    "scaled_dot_product_attention",
    "Sequential",
    "Sigmoid",
    "Softmax",
    "sparse_attention",
    "linear_attention",
    "paged_attention",
    "sparse",
    "SwiGLU",
    "Tanh",
    "transformer",
    "TransformerBlock",
    "create_causal_mask",
    "create_sinusoidal_embeddings",
]
